"""add user media table

Revision ID: 4f5669028823
Revises: d0bad0a4a7b0
Create Date: 2026-01-17 19:54:26.759154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f5669028823'
down_revision: Union[str, Sequence[str], None] = 'd0bad0a4a7b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_media',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('profile_picture', sa.String(), nullable=True),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_media')
    # ### end Alembic commands ###
