"""add user designation table

Revision ID: 85eb31306e07
Revises: 008d97b8ed5d
Create Date: 2026-01-17 19:43:10.229777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85eb31306e07'
down_revision: Union[str, Sequence[str], None] = '008d97b8ed5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_designations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('designation_type', sa.String(), nullable=False),
    sa.Column('registration_number', sa.String(), nullable=True),
    sa.Column('program', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('current_year', sa.Integer(), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('college_email', sa.String(), nullable=True),
    sa.Column('faculty_id', sa.String(), nullable=True),
    sa.Column('post', sa.String(), nullable=True),
    sa.Column('courses_taught', sa.String(), nullable=True),
    sa.Column('office_location', sa.String(), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('research', sa.String(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('linkedin', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_designations')
    # ### end Alembic commands ###
