"""add user general profile table

Revision ID: d0bad0a4a7b0
Revises: 85eb31306e07
Create Date: 2026-01-17 19:49:52.601348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0bad0a4a7b0'
down_revision: Union[str, Sequence[str], None] = '85eb31306e07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_general_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('short_bio', sa.String(), nullable=False),
    sa.Column('skills', sa.String(), nullable=False),
    sa.Column('interests', sa.String(), nullable=False),
    sa.Column('linkedin', sa.String(), nullable=True),
    sa.Column('github', sa.String(), nullable=True),
    sa.Column('portfolio', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_general_profiles')
    # ### end Alembic commands ###
